### ISSUE TITLE
Repo not automatically picked up on Advent of CodSpeed

### ISSUE THREAD

**Issue by adriencaccia** [fiorematteo/AoC2021#1]
Hey @fiorematteo, your repo fails to being picked up for the Advent of CodSpeed.

We run the `cargo modules structure --lib --max-depth=1 -p aoc-2024` command (using [`cargo-modules`](https://crates.io/crates/cargo-modules)) at the root of your repo to check that the `dayN` module exists, but it fails in your repo.
You can see why here: https://github.com/CodSpeedHQ/Advent/actions/runs/12281202554/job/34269553255#step:5:40

I tried manually bypassing the check and making the run on your repo, but your functions are `private`, so it still fails: 
https://github.com/CodSpeedHQ/Advent/actions/runs/12281349835/job/34269986178

If you still want to have your runs registered in the event, you can check those issues 😉

**Comment by fiorematteo** [comment]
Thanks for taking the time. I changed my functions to be public.
There is some weirdness about how cargo-aoc handles workspaces which might explain why you can't find the module (on my machine it works fine).
Either way I'm not skilled enough to get any points on the leaderboard so there is no need to get it working.

**Comment by ninomerlino** [comment]
That's not true. You are very smart!
